---
title: "Mini Project 4"
author: "Zhu Shen"
date: "April 28, 2018"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
#Load required library
library(mdsr)
library(RMySQL)
library(tidyverse)
library(ggplot2)
library(plotly)
library(gridExtra)
library(grid)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r, message = FALSE, warning = FALSE}
keyword_plot <- function(df){
  keyword_year <- function(df){
  keyword <- df %>%
  group_by(keyword)%>%
  summarize(num_keyword = n())%>%
  mutate(precentage = (num_keyword/ sum(num_keyword))*100) %>%
  arrange(desc(precentage)) %>%
  head(15)
  }
  myplot <- ggplot(keyword_year(df), aes(x = keyword, y = num_keyword)) + geom_bar(stat = 'identity', fill = 'darkgoldenrod4') + theme_classic() + theme(
  axis.text.x = element_text(angle = 50, hjust = 1, color = 'forestgreen'),
  panel.background = element_rect(fill = 'khaki2'),
  axis.title = element_text(color = 'forestgreen'),
  axis.ticks = element_line(color = 'forestgreen'),
  axis.line = element_line(color = 'forestgreen'),
  axis.text.y = element_text(color = 'forestgreen'),
  plot.title = element_text(color = 'skyblue3')
) 
  return(myplot)
}
```

```{r,message=FALSE, warning = FALSE}
#Find the number of movies each year
all_film<-db %>%
  dbGetQuery('SELECT production_year, COUNT(id) AS num_films 
              FROM imdb.title
              WHERE kind_id = 1
              GROUP BY production_year')

#Find the number of western films each year
western_film<-db %>%
  dbGetQuery('SELECT t.production_year, COUNT(mi.movie_id) AS num_westerns
              FROM imdb.movie_info mi 
              JOIN title t ON t.id = mi.movie_id
              WHERE info_type_id= 3
              AND info LIKE "%Western%"
              AND t.kind_id=1
              GROUP BY t.production_year;')

#Join two tables and find the percentage of western film
western_percent <- left_join (western_film,all_film,by= 'production_year') %>%
  mutate(percentage=(num_westerns/num_films)*100) %>%
  filter(production_year >=1900 & production_year <= 2017)
western_percent <- na.omit(western_percent)
western_percent$era <- lapply(western_percent$production_year, FUN = era)
```


```{r, message = FALSE, warning = FALSE}
western_plot_1 <- ggplot(data=western_percent,aes(x=production_year,y=percentage))+
  labs(x = "Year", y = "Percent of Western Movies") +
  labs(title = "Percent of Western Movies from 1900-2020", 
           caption = "Source: AAA") +
  scale_x_continuous(limits = c(1900,2017), breaks = c(1900, 1920, 1940, 1960, 1980, 2000, 2020),
                   label = c("1900", "1920", "1940", "1960", "1980", "2000", "2020"))+
  theme_classic()+
  theme(panel.background = element_rect(fill = "#EBF5FB"),
        panel.grid = element_blank(),
        axis.line = element_blank(), 
        axis.ticks = element_line(color = "snow4"), 
        axis.ticks.length = unit(0.5, "lines"),
        axis.text = element_text(size = 10, color = "black"),
        plot.title = element_text(family = "Helvetica", 
                                  face = "bold",
                                  size = 15, 
                                  color = "black")) +
  geom_line(color = "#5DADE2")+
  geom_area(fill = "#5DADE2")+ 
  geom_point(x = 1925, y= 8.8753, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1911, y = 8.1379, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1918, y = 3.0329, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1933, y = 2.5979, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1963, y = 1.50134, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1966, y = 3.41384, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1997, y = 0.09676, size = 2, shape = 21, fill = "white") +
  geom_point(x = 1990, y = 0.28533, size = 2, shape = 21, fill = "white")


western_plot_2 <- ggplot(data=western_percent,aes(x=production_year,y=percentage))+
  theme_classic() + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_blank(), 
        axis.ticks = element_line(color = "snow4"), 
        axis.ticks.length = unit(0.5, "lines"),
        axis.text = element_text(size = 10, color = "black"),
        plot.title = element_text(family = "Helvetica", 
                                  face = "bold",
                                  size = 15, 
                                  color = "black")) + 
  labs(x = "Year", y = "Percent of Western Movies") +
  labs(title = "Percent of Western Movies from 1900-2017", 
           caption = "Source: ") +
  scale_x_continuous(limits = c(1895,2017), breaks = c(1900, 1920, 1940, 1960, 1980, 2000, 2020),
                   label = c("1900", "1920", "1940", "1960", "1980", "2000", "2020")) +
  scale_y_continuous(limits = c(0,10), breaks = c(0, 2.5, 5, 7.5, 10),
                   label = c("0", "2.5", "5", "7.5", "10")) +
  annotate("rect", xmin = 1895, xmax = 1904, ymin = 0, ymax = Inf, fill = "#F7DC6F", alpha = 0.3) +
  annotate("rect", xmin = 1904, xmax = 1914, ymin = 0, ymax = Inf, fill = "#F39C12", alpha = 0.3) +
  annotate("rect", xmin = 1914, xmax = 1923, ymin = 0, ymax = Inf, fill = "#8E44AD", alpha = 0.3) +
  annotate("rect", xmin = 1923, xmax = 1940, ymin = 0, ymax = Inf, fill = "#21618C", alpha = 0.3) +
  annotate("rect", xmin = 1940, xmax = 1950, ymin = 0, ymax = Inf, fill = "#2ECC71", alpha = 0.3) +
  annotate("rect", xmin = 1950, xmax = 1960, ymin = 0, ymax = Inf, fill = "#EC7063", alpha = 0.3) +
  annotate("rect", xmin = 1960, xmax = 1970, ymin = 0, ymax = Inf, fill = "#85929E", alpha = 0.3) +
  annotate("rect", xmin = 1970, xmax = 1980, ymin = 0, ymax = Inf, fill = "#138D75", alpha = 0.3) +
  annotate("rect", xmin = 1980, xmax = 2017, ymin = 0, ymax = Inf, fill = "#5DADE2", alpha = 0.3) +
  geom_line()+
  geom_line(aes(y=percentage), size = 0.725) +
  annotate("text", x = c(1900, 1909, 1918.5, 1931.5, 1945, 1955, 1965, 1975, 2000), y = c(9.5,9.5, 9.5, 9.5, 9.5, 9.5, 9.5,9.5,9.5), label = c("Birth", "Mature", "WWI","Sound\nEra", "WWII", "Asian\nGolden\nAge", "Holly\nwood\nDecline", "New\nHolly\nwood", "Diversity\n& Tech"), color = c("#F39C12", "#F39C12", "#8E44AD", "#21618C", "#2ECC71", "#EC7063", "#85929E", "#138D75", "#5DADE2"),size = 4, family = "Helvetica")
  
ggplotly(western_plot_1) %>%
  layout(annotations = list(x = 1911, y = 8.8, text = "Relocate to \nHollywood", showarrow = F)) %>%
  layout(annotations = list(x = 1918, y = 2.4, text = "End of \nWWI", showarrow = F)) %>%
  layout(annotations = list(x = 1936, y = 8.8, text = "Greatest-ever \nOutput Era", showarrow = F)) %>%
  layout(annotations = list(x = 1933, y = 2, text = "Great \nDepression", showarrow = F)) %>%
  layout(annotations = list(x = 1963, y = 0.8, text = "More Movies \nProduce Abroad", showarrow = F)) %>%
  layout(annotations = list(x = 1966, y = 4.5, text = "Cultural Revolution\n & Abolition of\n the Hays Code", showarrow = F)) %>%
  layout(annotations = list(x = 2001, y = 0.78, text = "Invention\nof DVD", showarrow = F)) %>%
  layout(annotations = list(x = 1985, y = 0.95, text = "Start of New\nBollywood", showarrow = F))

western_plot_2

```

```{r,message = FALSE, warning = FALSE}
#Use index 3 to find genre of each movie
golden_1930_1960 <- db %>%
  dbGetQuery("SELECT mi.movie_id, k.keyword,t.title,t.production_year
              FROM imdb.movie_keyword mk
              JOIN keyword k ON k.id = mk.keyword_id
              JOIN title t ON t.id = mk.movie_id
              JOIN movie_info mi ON t.id =  mi.movie_id 
              WHERE mi. info_type_id = 3
              AND mi.info LIKE '%western%'
              AND production_year >= 1930 
              AND production_year <= 1960;")
keyword_plot(golden_1930_1960)


```


